<a href="https://colab.research.google.com/github/IamAbhinav01/RENET---Movie-Recomendation-Backend/blob/master/RENET.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
print("Hello World")

Hello World

GOING TO INSTALL THE postgresql && redis APT for colab -- vm version

iam refering this one for postgresql: https://colab.research.google.com/github/tensorflow/io/blob/master/docs/tutorials/postgresql.ipynb#scrollTo=YUj0878jPyz7

and for redis :https://colab.research.google.com/drive/1jPgmnGdlVPLQq3c9YqAsxc_gu6YReKaS?usp=sharing#scrollTo=-MfrA0Ykepy0

In [2]:
!sudo apt-get -y -qq update
!sudo apt-get -y -qq install postgresql
!sudo apt-get update -qq
!sudo apt-get install -y redis-server
%pip install redis

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
redis-server is already the newest version (5:6.0.16-1ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 26 not upgraded.
Requirement already satisfied: redis in /usr/local/lib/python3.12/dist-packages (8.1.0)

Installing the nesscery requirements

In [1]:
%pip install pandas==2.2.2 numpy==1.26.4 scikit-learn==1.5.0 implicit==0.7.2 sentence-transformers==3.0.1 faiss-cpu==1.8.0 lightgbm==4.4.0 SQLAlchemy==2.0.31 psycopg2-binary==2.9.9 python-dotenv==1.0.1 tqdm==4.66.4 scipy==1.13.1

Requirement already satisfied: pandas==2.2.2 in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)
Requirement already satisfied: scikit-learn==1.5.0 in /usr/local/lib/python3.12/dist-packages (1.5.0)
Requirement already satisfied: implicit==0.7.2 in /usr/local/lib/python3.12/dist-packages (0.7.2)
Requirement already satisfied: sentence-transformers==3.0.1 in /usr/local/lib/python3.12/dist-packages (3.0.1)
Requirement already satisfied: faiss-cpu==1.8.0 in /usr/local/lib/python3.12/dist-packages (1.8.0)
Requirement already satisfied: lightgbm==4.4.0 in /usr/local/lib/python3.12/dist-packages (4.4.0)
Requirement already satisfied: SQLAlchemy==2.0.31 in /usr/local/lib/python3.12/dist-packages (2.0.31)
Requirement already satisfied: psycopg2-binary==2.9.9 in /usr/local/lib/python3.12/dist-packages (2.9.9)
Requirement already satisfied: python-dotenv==1.0.1 in /usr/local/lib/python3.12/dist-packages (1.0.1)
Requirement already satisfied: tqdm==4.66.4 in /usr/local/lib/python3.12/dist-packages (4.66.4)
Requirement already satisfied: scipy==1.13.1 in /usr/local/lib/python3.12/dist-packages (1.13.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2026.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn==1.5.0) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.34.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==3.0.1) (4.57.6)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==3.0.1) (2.11.0+cpu)
Requirement already satisfied: huggingface-hub>=0.15.1 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==3.0.1) (0.36.2)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers==3.0.1) (11.3.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy==2.0.31) (4.16.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy==2.0.31) (3.5.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers==3.0.1) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers==3.0.1) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers==3.0.1) (1.5.1)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers==3.0.1) (26.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers==3.0.1) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.15.1->sentence-transformers==3.0.1) (2.32.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==3.0.1) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==3.0.1) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==3.0.1) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers==3.0.1) (3.1.6)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.34.0->sentence-transformers==3.0.1) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.34.0->sentence-transformers==3.0.1) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.34.0->sentence-transformers==3.0.1) (0.8.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers==3.0.1) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers==3.0.1) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers==3.0.1) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers==3.0.1) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers==3.0.1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.15.1->sentence-transformers==3.0.1) (2026.6.17)

why these => {
  implicit -- Collaborative filtering/recommendation algorithms
  sentence-transformers -- Text Embeddings
  lightgbm -- Gradient Boosting / ranking the models
  SQLAlchemy -- database ORM
}

STARTING THE SERVICES

In [3]:
!sudo service postgresql start
!service redis-server start

 * Starting PostgreSQL 14 database server
   ...done.
Starting redis-server: redis-server.

STATUS CHECKING

In [4]:
import redis

client = redis.Redis(
    host="localhost",
    port=6379,
    decode_responses=True
)

print("Redis:", client.ping())

Redis: True

In [5]:
!service postgresql status

14/main (port 5432): online

In [6]:
!ps aux | grep redis

redis       7711  0.0  0.0  67212  6600 ?        Ssl  09:02   0:00 /usr/bin/redis-server 127.0.0.1:6379
root        7728  0.0  0.0   7372  3424 ?        S    09:02   0:00 /bin/bash -c ps aux | grep redis
root        7730  0.0  0.0   6480  2424 ?        S    09:02   0:00 grep redis

creating a PostgreSQL user and a PostgreSQL database

In [7]:
!sudo -u postgres psql -c "CREATE USER renet WITH PASSWORD 'renet';"

CREATE ROLE

In [8]:
!sudo -u postgres psql -c "CREATE DATABASE renet OWNER renet;"

CREATE DATABASE

Connecting env variables

In [9]:
from google.colab import userdata
password = userdata.get('POSTGRES_PASSWORD')

In [10]:
env_credentials = f"""DATABASE_URL=postgresql://renet:{password}
REDIS_URL=redis://localhost:6379/0
"""

with open(".env", "w") as f:
    f.write(env_credentials)

print("Created .env")

Created .env

Found a Dataset called as MOVIELENS
implicit → collaborative filtering
sentence-transformers → content/text embeddings
faiss-cpu → vector similarity search
LightGBM → ranking/recommendation

In [11]:
!mkdir -p data
!cd data && curl -L -o ml-latest-small.zip https://files.grouplens.org/datasets/movielens/ml-latest-small.zip
!cd data && unzip -q ml-latest-small.zip
!rm data/ml-latest-small.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  955k  100  955k    0     0  1505k      0 --:--:-- --:--:-- --:--:-- 1504k

In [12]:
from dotenv import load_dotenv
import os
load_dotenv()

True

In [13]:
DATABASE_URL = os.getenv("DATABASE_URL")
DATA_DIR = os.environ.get("DATA_DIR", "./data/ml-latest-small")

In [14]:
import pandas as pd
print("\n--- Dataset files ---")

for file in os.listdir(DATA_DIR):
    if file.endswith(".csv"):
        file_path = os.path.join(DATA_DIR, file)

        df = pd.read_csv(file_path)

        print(f"\n===== {file} =====")
        print(df.head(5))

--- Dataset files ---

===== tags.csv =====
   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

===== links.csv =====
   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

===== ratings.csv =====
   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

===== movies.csv =====
   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy

DATABASE SCHEMA

                ARCHITECTURE OF DATABASE
                
                
                 PostgreSQL
                     │
       ┌─────────────┼─────────────┐
       │             │             │
     users         items      interactions
       │             │             │
       │             │             │
       └─────────────┴─────────────┘
                     │
              Recommendation
                  System

One user → many interactions
One movie → many interactions

CASCADE means PostgreSQL will also remove objects that depend on those tables

THE kind of table iam paling is {
   | id | title     | genres                       | primary_genre |
| -: | --------- | ---------------------------- | ------------- |
|  1 | Toy Story | Adventure|Animation|Children | Animation     |
|  2 | Jumanji   | Adventure|Children|Fantasy   | Adventure     |

}

and the interaction table is {
| id | user_id | item_id | rating | event_type | created_at |
| -: | ------: | ------: | -----: | ---------- | ---------- |
|  1 |       1 |       1 |    5.0 | rating     | ...        |
|  2 |       1 |       3 |    4.0 | rating     | ...        |
|  3 |       2 |       1 |    3.5 | rating     | ...        |
}

In [15]:
SQL_SCHEMA = """
DROP TABLE IF EXISTS interactions CASCADE;
DROP TABLE IF EXISTS items CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id INTEGER PRIMARY KEY
);

CREATE TABLE items (
    id INTEGER PRIMARY KEY,
    title TEXT NOT NULL,
    genres TEXT NOT NULL,
    primary_genre TEXT NOT NULL
);

CREATE TABLE interactions (
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    item_id INTEGER NOT NULL REFERENCES items(id),
    rating REAL NOT NULL,
    event_type TEXT NOT NULL DEFAULT 'rating',
    created_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_interactions_user ON interactions(user_id);
CREATE INDEX idx_interactions_item ON interactions(item_id);

"""

DATA INGESTION

**MovieLens CSV files → transforms them → creates PostgreSQL tables → inserts the data.**

In [16]:
movies_path = os.path.join(DATA_DIR, "movies.csv")
ratings_path = os.path.join(DATA_DIR, "ratings.csv")

In [17]:
if not os.path.exists(movies_path) or not os.path.exists(ratings_path):
  print(f"ERROR: expected {movies_path} and {ratings_path}.")
  print("Run: bash data/download_data.sh   (or download MovieLens manually)")
  sys.exit(1)

In [18]:
movies = pd.read_csv(movies_path)
ratings = pd.read_csv(ratings_path)

In [19]:
movies["primary_genre"] = movies["genres"].str.split("|").str[0].fillna("Unknown")

sqlAlchemy -> https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_engine

In [20]:
from sqlalchemy import create_engine,text

In [21]:
engine = create_engine(DATABASE_URL)

              INTEND TODO THIS STRUCTURE
              MovieLens
                  │
        ┌─────────┴─────────┐
        │                   │
    movies.csv          ratings.csv
        │                   │
        ▼                   ▼
     Pandas              Pandas
        │                   │
        ▼                   ├──────────────┐
     items                  │              │
        │                   ▼              ▼
        │                unique users    ratings
        │                   │              │
        ▼                   ▼              ▼
    PostgreSQL           users        interactions

In [22]:
with engine.begin() as conn:
    print("Creating schema...")

    for stmt in SQL_SCHEMA.split(";"):
        if stmt.strip():
            conn.execute(text(stmt))

    print(f"Loading {len(movies)} items...")

    movies[["movieId", "title", "genres", "primary_genre"]].rename(
        columns={"movieId": "id"}
    ).to_sql(
        "items",
        conn,
        if_exists="append",
        index=False
    )

    print(f"Loading {ratings.userId.nunique()} users...")

    pd.DataFrame(
        {"id": ratings.userId.unique()}
    ).to_sql(
        "users",
        conn,
        if_exists="append",
        index=False
    )

    print(f"Loading {len(ratings)} interactions...")

    ratings_out = ratings.rename(
        columns={
            "userId": "user_id",
            "movieId": "item_id"
        }
    )[["user_id", "item_id", "rating"]]

    ratings_out["event_type"] = "rating"

    ratings_out.to_sql(
        "interactions",
        conn,
        if_exists="append",
        index=False
    )

print("Done. Data loaded into Postgres.")

Creating schema...
Loading 9742 items...
Loading 610 users...
Loading 100836 interactions...
Done. Data loaded into Postgres.

In [23]:
POSITIVE_RATING_THRESHOLD = 4.0
FACTORS = 64
REGULARIZATION = 0.05
ITERATIONS = 20

In [24]:
MODELS_DIR = os.environ.get("MODELS_DIR", "./models")

In [25]:
os.makedirs(MODELS_DIR, exist_ok=True)
engine = create_engine(DATABASE_URL)

In [26]:
interactions = pd.read_sql("SELECT user_id, item_id, rating FROM interactions", engine)

In [27]:
interactions

        user_id  item_id  rating
0             1        1     4.0
1             1        3     4.0
2             1        6     4.0
3             1       47     5.0
4             1       50     5.0
...         ...      ...     ...
100831      610   166534     4.0
100832      610   168248     5.0
100833      610   168250     5.0
100834      610   168252     5.0
100835      610   170875     3.0

[100836 rows x 3 columns]

implicit feedbcak

In [28]:
interactions = interactions[interactions.rating >= POSITIVE_RATING_THRESHOLD]

In [29]:
interactions

        user_id  item_id  rating
0             1        1     4.0
1             1        3     4.0
2             1        6     4.0
3             1       47     5.0
4             1       50     5.0
...         ...      ...     ...
100830      610   166528     4.0
100831      610   166534     4.0
100832      610   168248     5.0
100833      610   168250     5.0
100834      610   168252     5.0

[48580 rows x 3 columns]

In [30]:
print(f"Training ALS on {len(interactions)} positive interactions "
f"({interactions.user_id.nunique()} users, {interactions.item_id.nunique()} items)")

Training ALS on 48580 positive interactions (609 users, 6298 items)

MovieLens ID → Matrix index

In [31]:
user_ids = interactions.user_id.astype("category")
item_ids = interactions.item_id.astype("category")

user-item interaction matrix

In [32]:
from scipy.sparse import coo_matrix
import numpy as np
from implicit.als import AlternatingLeastSquares
import pickle

In [33]:
user_item = coo_matrix( ( np.ones(len(interactions), dtype=np.float32), ( user_ids.cat.codes, item_ids.cat.codes ) ) ).tocsr()

In [34]:
print(user_item.shape)

(609, 6298)

In [35]:
model = AlternatingLeastSquares( factors=FACTORS, regularization=REGULARIZATION, iterations=ITERATIONS )

/usr/local/lib/python3.12/dist-packages/implicit/cpu/als.py:95: RuntimeWarning: OpenBLAS is configured to use 2 threads. It is highly recommended to disable its internal threadpool by setting the environment variable 'OPENBLAS_NUM_THREADS=1' or by calling 'threadpoolctl.threadpool_limits(1, "blas")'. Having OpenBLAS use a threadpool can lead to severe performance issues here.
  check_blas_config()

Train the model

In [36]:
model.fit(user_item)

  0%|          | 0/20 [00:00<?, ?it/s]

In [37]:
artifact = {
        "model": model,
        "user_id_to_idx": {uid: idx for idx, uid in enumerate(user_ids.cat.categories)},
        "idx_to_user_id": dict(enumerate(user_ids.cat.categories)),
        "item_id_to_idx": {iid: idx for idx, iid in enumerate(item_ids.cat.categories)},
        "idx_to_item_id": dict(enumerate(item_ids.cat.categories)),
        "user_item_matrix": user_item,
    }

In [38]:
out_path = os.path.join(MODELS_DIR, "als_model.pkl")
with open(out_path, "wb") as f:
    pickle.dump(artifact, f)

print(f"Saved {out_path}")

Saved ./models/als_model.pkl

EMBEDDINGS GENERATION

In [39]:
items = pd.read_sql("SELECT id, title, genres FROM items ORDER BY id", engine)
text = (items["title"] + ". " + items["genres"].str.replace("|", " ", regex=False)).tolist()

In [40]:
from sentence_transformers import SentenceTransformer

WARNING:torchao.kernel.intmm:Warning: Detected no triton, on systems without Triton certain kernels will not work

In [41]:
print(f"Embedding {len(text)} items with all-MiniLM-L6-v2 (CPU is fine, ~1-2 min for this size)...")
model = SentenceTransformer("all-MiniLM-L6-v2")
embeddings = model.encode(text, show_progress_bar=True, batch_size=64).astype("float32")

Embedding 9742 items with all-MiniLM-L6-v2 (CPU is fine, ~1-2 min for this size)...

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/153 [00:00<?, ?it/s]

In [42]:
np.save(os.path.join(MODELS_DIR, "content_embeddings.npy"), embeddings)
np.save(os.path.join(MODELS_DIR, "content_item_ids.npy"), items["id"].to_numpy())
print(f"Saved embeddings with shape {embeddings.shape}")

Saved embeddings with shape (9742, 384)

Semantic Similarity

In [43]:
import faiss

In [44]:
embeddings = np.load(os.path.join(MODELS_DIR, "content_embeddings.npy")).astype("float32")
faiss.normalize_L2(embeddings)

In [45]:
embeddings.shape

(9742, 384)

In [46]:
index = faiss.IndexFlatIP(embeddings.shape[1])
index.add(embeddings)

In [47]:
out_path = os.path.join(MODELS_DIR, "content.index")
faiss.write_index(index, out_path)
print(f"Saved FAISS index with {index.ntotal} vectors to {out_path}")

Saved FAISS index with 9742 vectors to ./models/content.index

Learning-to-Rank (LTR) model
ALS + content similarity + popularity + genre information → features → ranking model learns how to score candidate movies.

User liked:
Movie 10
Movie 20
Movie 30

Positive = 3

Negative target = 3 × 2 = 6

So the training data might contain:

3 positive
6 negative

In [48]:
NEGATIVES_PER_USER_MULTIPLIER = 2
MIN_RATINGS_PER_USER = 5

In [49]:
def load_artifacts():
    with open(os.path.join(MODELS_DIR, "als_model.pkl"), "rb") as f:
        als = pickle.load(f)
    content_embeddings = np.load(os.path.join(MODELS_DIR, "content_embeddings.npy"))
    content_item_ids = np.load(os.path.join(MODELS_DIR, "content_item_ids.npy"))
    item_id_to_row = {iid: i for i, iid in enumerate(content_item_ids)}
    return als, content_embeddings, item_id_to_row

In [50]:
engine = create_engine(DATABASE_URL)
interactions = pd.read_sql("SELECT user_id, item_id, rating, created_at FROM interactions", engine)
items = pd.read_sql("SELECT id, primary_genre FROM items", engine)
item_genre = dict(zip(items.id, items.primary_genre))

In [51]:
interactions

        user_id  item_id  rating                 created_at
0             1        1     4.0 2026-08-14 09:02:34.145998
1             1        3     4.0 2026-08-14 09:02:34.145998
2             1        6     4.0 2026-08-14 09:02:34.145998
3             1       47     5.0 2026-08-14 09:02:34.145998
4             1       50     5.0 2026-08-14 09:02:34.145998
...         ...      ...     ...                        ...
100831      610   166534     4.0 2026-08-14 09:02:34.145998
100832      610   168248     5.0 2026-08-14 09:02:34.145998
100833      610   168250     5.0 2026-08-14 09:02:34.145998
100834      610   168252     5.0 2026-08-14 09:02:34.145998
100835      610   170875     3.0 2026-08-14 09:02:34.145998

[100836 rows x 4 columns]

In [52]:
item_genre

{1: 'Adventure',
 2: 'Adventure',
 3: 'Comedy',
 4: 'Comedy',
 5: 'Comedy',
 6: 'Action',
 7: 'Comedy',
 8: 'Adventure',
 9: 'Action',
 10: 'Action',
 11: 'Comedy',
 12: 'Comedy',
 13: 'Adventure',
 14: 'Drama',
 15: 'Action',
 16: 'Crime',
 17: 'Drama',
 18: 'Comedy',
 19: 'Comedy',
 20: 'Action',
 21: 'Comedy',
 22: 'Crime',
 23: 'Action',
 24: 'Drama',
 25: 'Drama',
 26: 'Drama',
 27: 'Children',
 28: 'Drama',
 29: 'Adventure',
 30: 'Crime',
 31: 'Drama',
 32: 'Mystery',
 34: 'Children',
 36: 'Crime',
 38: 'Children',
 39: 'Comedy',
 40: 'Drama',
 41: 'Drama',
 42: 'Action',
 43: 'Drama',
 44: 'Action',
 45: 'Comedy',
 46: 'Drama',
 47: 'Mystery',
 48: 'Animation',
 49: 'Drama',
 50: 'Crime',
 52: 'Comedy',
 53: 'Adventure',
 54: 'Children',
 55: 'Drama',
 57: 'Drama',
 58: 'Comedy',
 60: 'Adventure',
 61: 'Drama',
 62: 'Drama',
 63: 'Comedy',
 64: 'Comedy',
 65: 'Comedy',
 66: 'Action',
 68: 'Comedy',
 69: 'Comedy',
 70: 'Action',
 71: 'Action',
 72: 'Comedy',
 73: 'Drama',
 74: 'Drama',
 75: 'Comedy',
 76: 'Action',
 77: 'Documentary',
 78: 'Action',
 79: 'Drama',
 80: 'Children',
 81: 'Crime',
 82: 'Comedy',
 83: 'Drama',
 85: 'Drama',
 86: 'Action',
 87: 'Children',
 88: 'Comedy',
 89: 'Action',
 92: 'Drama',
 93: 'Comedy',
 94: 'Comedy',
 95: 'Action',
 96: 'Comedy',
 97: 'Crime',
 99: 'Documentary',
 100: 'Drama',
 101: 'Adventure',
 102: 'Comedy',
 103: 'Mystery',
 104: 'Comedy',
 105: 'Drama',
 106: 'Comedy',
 107: 'Adventure',
 108: 'Documentary',
 110: 'Action',
 111: 'Crime',
 112: 'Action',
 113: 'Drama',
 116: 'Documentary',
 117: 'Crime',
 118: 'Comedy',
 119: 'Comedy',
 121: 'Drama',
 122: 'Comedy',
 123: 'Drama',
 125: 'Comedy',
 126: 'Adventure',
 128: 'Documentary',
 129: 'Comedy',
 132: 'Thriller',
 135: 'Comedy',
 137: 'Documentary',
 140: 'Drama',
 141: 'Comedy',
 144: 'Comedy',
 145: 'Action',
 146: 'Adventure',
 147: 'Drama',
 148: 'Drama',
 149: 'Crime',
 150: 'Adventure',
 151: 'Action',
 152: 'Drama',
 153: 'Action',
 154: 'Drama',
 155: 'Adventure',
 156: 'Comedy',
 157: 'Comedy',
 158: 'Adventure',
 159: 'Crime',
 160: 'Action',
 161: 'Drama',
 162: 'Documentary',
 163: 'Action',
 164: 'Crime',
 165: 'Action',
 166: 'Comedy',
 168: 'Action',
 169: 'Adventure',
 170: 'Action',
 171: 'Comedy',
 172: 'Action',
 173: 'Action',
 174: 'Comedy',
 175: 'Drama',
 176: 'Comedy',
 177: 'Horror',
 178: 'Comedy',
 179: 'Drama',
 180: 'Comedy',
 181: 'Action',
 183: 'Comedy',
 184: 'Drama',
 185: 'Action',
 186: 'Comedy',
 187: 'Comedy',
 188: 'Fantasy',
 189: 'Comedy',
 190: 'Thriller',
 191: 'Drama',
 193: 'Drama',
 194: 'Comedy',
 195: 'Comedy',
 196: 'Horror',
 198: 'Action',
 199: 'Drama',
 201: 'Drama',
 202: 'Drama',
 203: 'Comedy',
 204: 'Action',
 205: 'Comedy',
 206: 'Documentary',
 207: 'Drama',
 208: 'Action',
 209: 'Drama',
 210: 'Western',
 211: 'Drama',
 212: 'Adventure',
 213: 'Drama',
 214: 'Drama',
 215: 'Drama',
 216: 'Comedy',
 217: 'Drama',
 218: 'Comedy',
 219: 'Drama',
 220: 'Horror',
 222: 'Drama',
 223: 'Comedy',
 224: 'Comedy',
 225: 'Drama',
 227: 'Action',
 228: 'Comedy',
 229: 'Drama',
 230: 'Drama',
 231: 'Adventure',
 232: 'Comedy',
 233: 'Drama',
 234: 'Comedy',
 235: 'Comedy',
 236: 'Action',
 237: 'Comedy',
 238: 'Adventure',
 239: 'Animation',
 240: 'Thriller',
 241: 'Children',
 242: 'Drama',
 243: 'Children',
 246: 'Documentary',
 247: 'Crime',
 248: 'Comedy',
 249: 'Drama',
 250: 'Children',
 251: 'Action',
 252: 'Comedy',
 253: 'Drama',
 254: 'Drama',
 255: 'Comedy',
 256: 'Comedy',
 257: 'Mystery',
 258: 'Adventure',
 259: 'Crime',
 260: 'Action',
 261: 'Drama',
 262: 'Children',
 263: 'Drama',
 265: 'Drama',
 266: 'Drama',
 267: 'Comedy',
 269: 'Drama',
 270: 'Drama',
 271: 'Drama',
 272: 'Comedy',
 273: 'Drama',
 274: 'Comedy',
 275: 'Comedy',
 276: 'Comedy',
 277: 'Drama',
 278: 'Comedy',
 279: 'Drama',
 280: 'Drama',
 281: 'Comedy',
 282: 'Drama',
 283: 'Crime',
 284: 'Action',
 285: 'Drama',
 287: 'Comedy',
 288: 'Action',
 289: 'Comedy',
 290: 'Crime',
 291: 'Drama',
 292: 'Action',
 293: 'Action',
 294: 'Comedy',
 295: 'Comedy',
 296: 'Comedy',
 298: 'Drama',
 299: 'Drama',
 300: 'Drama',
 301: 'Drama',
 302: 'Drama',
 303: 'Action',
 304: 'Comedy',
 305: 'Comedy',
 306: 'Drama',
 307: 'Drama',
 308: 'Comedy',
 310: 'Comedy',
 311: 'Horror',
 312: 'Comedy',
 313: 'Animation',
 314: 'Children',
 315: 'Action',
 316: 'Action',
 317: 'Comedy',
 318: 'Crime',
 319: 'Comedy',
 320: 'Film-Noir',
 321: 'Drama',
 322: 'Comedy',
 324: 'Comedy',
 325: 'Comedy',
 326: 'Drama',
 327: 'Action',
 328: 'Horror',
 329: 'Adventure',
 330: 'Action',
 331: 'Drama',
 332: 'Horror',
 333: 'Comedy',
 334: 'Drama',
 335: 'Mystery',
 336: 'Drama',
 337: 'Drama',
 338: 'Action',
 339: 'Comedy',
 340: 'Adventure',
 341: 'Drama',
 342: 'Comedy',
 343: 'Children',
 344: 'Comedy',
 345: 'Comedy',
 346: 'Drama',
 347: 'Drama',
 348: 'Comedy',
 349: 'Action',
 350: 'Drama',
 351: 'Comedy',
 352: 'Comedy',
 353: 'Action',
 354: 'Drama',
 355: 'Children',
 356: 'Comedy',
 357: 'Comedy',
 358: 'Drama',
 359: 'Comedy',
 360: 'Action',
 361: 'Comedy',
 362: 'Adventure',
 363: 'Documentary',
 364: 'Adventure',
 365: 'Drama',
 366: 'Drama',
 367: 'Action',
 368: 'Adventure',
 369: 'Drama',
 370: 'Action',
 371: 'Comedy',
 372: 'Comedy',
 373: 'Thriller',
 374: 'Children',
 376: 'Action',
 377: 'Action',
 378: 'Comedy',
 379: 'Action',
 380: 'Action',
 381: 'Drama',
 382: 'Drama',
 383: 'Western',
 384: 'Action',
 385: 'Drama',
 386: 'Drama',
 387: 'Action',
 388: 'Drama',
 389: 'Drama',
 390: 'Action',
 391: 'Crime',
 393: 'Action',
 405: 'Action',
 406: 'Drama',
 407: 'Horror',
 408: 'Drama',
 409: 'Crime',
 410: 'Children',
 412: 'Drama',
 413: 'Comedy',
 414: 'Comedy',
 415: 'Comedy',
 416: 'Western',
 417: 'Comedy',
 418: 'Drama',
 419: 'Comedy',
 420: 'Action',
 421: 'Adventure',
 422: 'Thriller',
 423: 'Action',
 424: 'Drama',
 425: 'Drama',
 426: 'Horror',
 427: 'Drama',
 428: 'Drama',
 429: 'Comedy',
 430: 'Comedy',
 431: 'Crime',
 432: 'Adventure',
 433: 'Comedy',
 434: 'Action',
 435: 'Comedy',
 436: 'Drama',
 437: 'Comedy',
 438: 'Action',
 440: 'Comedy',
 441: 'Comedy',
 442: 'Action',
 444: 'Comedy',
 445: 'Comedy',
 446: 'Drama',
 448: 'Drama',
 449: 'Comedy',
 450: 'Comedy',
 451: 'Drama',
 452: 'Drama',
 453: 'Comedy',
 454: 'Drama',
 455: 'Adventure',
 456: 'Crime',
 457: 'Thriller',
 458: 'Drama',
 459: 'Action',
 460: 'Comedy',
 461: 'Drama',
 464: 'Action',
 466: 'Action',
 467: 'Comedy',
 468: 'Comedy',
 469: 'Drama',
 470: 'Comedy',
 471: 'Comedy',
 472: 'Comedy',
 473: 'Comedy',
 474: 'Action',
 475: 'Drama',
 476: 'Comedy',
 477: 'Drama',
 478: 'Comedy',
 479: 'Action',
 480: 'Action',
 481: 'Drama',
 482: 'Crime',
 484: 'Adventure',
 485: 'Action',
 486: 'Comedy',
 487: 'Comedy',
 488: 'Drama',
 489: 'Comedy',
 490: 'Thriller',
 491: 'Drama',
 492: 'Comedy',
 493: 'Action',
 494: 'Action',
 495: 'Drama',
 496: 'Comedy',
 497: 'Comedy',
 499: 'Comedy',
 500: 'Comedy',
 501: 'Drama',
 502: 'Action',
 504: 'Action',
 505: 'Comedy',
 506: 'Drama',
 507: 'Crime',
 508: 'Drama',
 509: 'Drama',
 510: 'Drama',
 511: 'Action',
 512: 'Horror',
 513: 'Comedy',
 514: 'Comedy',
 515: 'Drama',
 516: 'Comedy',
 517: 'Action',
 518: 'Comedy',
 519: 'Action',
 520: 'Comedy',
 521: 'Crime',
 522: 'Action',
 523: 'Drama',
 524: 'Drama',
 526: 'Drama',
 527: 'Drama',
 528: 'Comedy',
 529: 'Drama',
 531: 'Children',
 532: 'Comedy',
 533: 'Action',
 534: 'Drama',
 535: 'Drama',
 536: 'Drama',
 537: 'Drama',
 538: 'Drama',
 539: 'Comedy',
 540: 'Thriller',
 541: 'Action',
 542: 'Comedy',
 543: 'Comedy',
 544: 'Action',
 546: 'Action',
 547: 'Action',
 548: 'Action',
 549: 'Drama',
 550: 'Comedy',
 551: 'Animation',
 552: 'Action',
 553: 'Action',
 555: 'Crime',
 556: 'Documentary',
 558: 'Action',
 562: 'Comedy',
 563: 'Drama',
 564: 'Comedy',
 567: 'Comedy',
 568: 'Comedy',
 569: 'Comedy',
 573: 'Drama',
 574: 'Comedy',
 575: 'Children',
 577: 'Adventure',
 579: 'Crime',
 580: 'Drama',
 581: 'Documentary',
 583: 'Comedy',
 585: 'Comedy',
 586: 'Children',
 587: 'Comedy',
 588: 'Adventure',
 589: 'Action',
 590: 'Adventure',
 592: 'Action',
 593: 'Crime',
 594: 'Animation',
 595: 'Animation',
 596: 'Animation',
 597: 'Comedy',
 599: 'Adventure',
 600: 'Action',
 602: 'Documentary',
 605: 'Drama',
 606: 'Fantasy',
 608: 'Comedy',
 609: 'Adventure',
 610: 'Action',
 611: 'Action',
 612: 'Comedy',
 613: 'Drama',
 615: 'Comedy',
 616: 'Animation',
 617: 'Comedy',
 618: 'Comedy',
 619: 'Comedy',
 626: 'Comedy',
 627: 'Drama',
 628: 'Crime',
 631: 'Adventure',
 632: 'Drama',
 633: 'Comedy',
 634: 'Comedy',
 635: 'Comedy',
 636: 'Drama',
 637: 'Comedy',
 638: 'Romance',
 639: 'Comedy',
 640: 'Drama',
 645: 'Drama',
 647: 'Action',
 648: 'Action',
 649: 'Comedy',
 650: 'Drama',
 653: 'Action',
 656: 'Comedy',
 661: 'Adventure',
 662: 'Thriller',
 663: 'Comedy',
 665: 'Comedy',
 667: 'Action',
 668: 'Drama',
 670: 'Drama',
 671: 'Comedy',
 673: 'Adventure',
 674: 'Adventure',
 678: 'Drama',
 679: 'Drama',
 680: 'Drama',
 685: 'Drama',
 688: 'Action',
 691: 'Comedy',
 692: 'Action',
 694: 'Action',
 695: 'Mystery',
 697: 'Drama',
 698: 'Drama',
 700: 'Comedy',
 703: 'Drama',
 704: 'Action',
 706: 'Drama',
 707: 'Crime',
 708: 'Comedy',
 709: 'Adventure',
 710: 'Comedy',
 711: 'Adventure',
 714: 'Drama',
 715: 'Drama',
 718: 'Comedy',
 719: 'Comedy',
 720: 'Adventure',
 722: 'Documentary',
 724: 'Drama',
 725: 'Comedy',
 726: 'Drama',
 728: 'Comedy',
 731: 'Crime',
 733: 'Action',
 735: 'Horror',
 736: 'Action',
 737: 'Action',
 741: 'Animation',
 742: 'Horror',
 743: 'Comedy',
 745: 'Animation',
 747: 'Comedy',
 748: 'Action',
 750: 'Comedy',
 757: 'Drama',
 759: 'Documentary',
 760: 'Drama',
 761: 'Action',
 762: 'Comedy',
 764: 'Drama',
 765: 'Comedy',
 766: 'Drama',
 773: 'Drama',
 775: 'Horror',
 778: 'Comedy',
 779: 'Drama',
 780: 'Action',
 781: 'Drama',
 782: 'Drama',
 783: 'Animation',
 784: 'Comedy',
 785: 'Comedy',
 786: 'Action',
 788: 'Comedy',
 790: 'Drama',
 791: 'Documentary',
 795: 'Drama',
 798: 'Action',
 799: 'Comedy',
 800: 'Drama',
 801: 'Children',
 802: 'Drama',
 803: 'Comedy',
 804: 'Comedy',
 805: 'Drama',
 806: 'Crime',
 808: 'Adventure',
 809: 'Action',
 810: 'Children',
 813: 'Comedy',
 818: 'Comedy',
 823: 'Drama',
 824: 'Drama',
 828: 'Adventure',
 829: 'Comedy',
 830: 'Comedy',
 832: 'Crime',
 833: 'Comedy',
 835: 'Drama',
 836: 'Action',
 837: 'Children',
 838: 'Comedy',
 839: 'Action',
 840: 'Children',
 841: 'Horror',
 842: 'Comedy',
 848: 'Drama',
 849: 'Action',
 851: 'Drama',
 852: 'Comedy',
 858: 'Crime',
 861: 'Action',
 866: 'Crime',
 867: 'Comedy',
 869: 'Crime',
 870: 'Comedy',
 875: 'Action',
 876: 'Action',
 879: 'Horror',
 880: 'Sci-Fi',
 881: 'Children',
 882: 'Drama',
 885: 'Children',
 886: 'Action',
 888: 'Adventure',
 889: 'Drama',
 891: 'Horror',
 892: 'Comedy',
 893: 'Drama',
 896: 'Drama',
 897: 'Adventure',
 898: 'Comedy',
 899: 'Comedy',
 900: 'Musical',
 901: 'Comedy',
 902: 'Drama',
 903: 'Drama',
 904: 'Mystery',
 905: 'Comedy',
 906: 'Drama',
 907: 'Comedy',
 908: 'Action',
 909: 'Comedy',
 910: 'Comedy',
 911: 'Comedy',
 912: 'Drama',
 913: 'Film-Noir',
 914: 'Comedy',
 915: 'Comedy',
 916: 'Comedy',
 917: 'Children',
 918: 'Musical',
 919: 'Adventure',
 920: 'Drama',
 921: 'Comedy',
 922: 'Drama',
 923: 'Drama',
 924: 'Adventure',
 926: 'Drama',
 927: 'Comedy',
 928: 'Drama',
 929: 'Drama',
 930: 'Film-Noir',
 931: 'Mystery',
 932: 'Drama',
 933: 'Crime',
 934: 'Comedy',
 935: 'Comedy',
 936: 'Comedy',
 937: 'Comedy',
 938: 'Musical',
 940: 'Action',
 941: 'Adventure',
 942: 'Crime',
 943: 'Drama',
 944: 'Drama',
 945: 'Comedy',
 946: 'Comedy',
 947: 'Comedy',
 948: 'Drama',
 949: 'Drama',
 950: 'Comedy',
 951: 'Comedy',
 952: 'Adventure',
 953: 'Children',
 954: 'Drama',
 955: 'Comedy',
 956: 'Drama',
 959: 'Drama',
 961: 'Drama',
 963: 'Musical',
 965: 'Drama',
 968: 'Horror',
 969: 'Adventure',
 970: 'Adventure',
 971: 'Drama',
 973: 'Comedy',
 976: 'Romance',
 979: 'Drama',
 981: 'Drama',
 982: 'Drama',
 984: 'Comedy',
 986: 'Adventure',
 987: 'Drama',
 988: 'Comedy',
 990: 'Action',
 991: 'Drama',
 993: 'Drama',
 994: 'Comedy',
 996: 'Action',
 998: 'Action',
 999: 'Crime',
 1003: 'Drama',
 1004: 'Action',
 1005: 'Children',
 1006: 'Drama',
 1007: 'Children',
 1008: 'Adventure',
 1009: 'Adventure',
 1010: 'Children',
 1011: 'Children',
 1012: 'Children',
 1013: 'Children',
 1014: 'Children',
 1015: 'Adventure',
 1016: 'Children',
 1017: 'Adventure',
 1018: 'Children',
 1019: 'Adventure',
 1020: 'Comedy',
 1021: 'Children',
 1022: 'Animation',
 1023: 'Animation',
 1024: 'Animation',
 1025: 'Animation',
 1027: 'Adventure',
 1028: 'Children',
 1029: 'Animation',
 1030: 'Adventure',
 1031: 'Adventure',
 1032: 'Adventure',
 1033: 'Animation',
 1034: 'Comedy',
 1035: 'Musical',
 1036: 'Action',
 1037: 'Action',
 1040: 'Drama',
 1041: 'Drama',
 1042: 'Comedy',
 1043: 'Drama',
 1046: 'Drama',
 1047: 'Action',
 1049: 'Action',
 1050: 'Documentary',
 1051: 'Drama',
 1053: 'Crime',
 1054: 'Drama',
 1055: 'Thriller',
 1056: 'Drama',
 1057: 'Comedy',
 1059: 'Drama',
 1060: 'Comedy',
 1061: 'Thriller',
 1064: 'Animation',
 1066: 'Comedy',
 1068: 'Crime',
 1073: 'Children',
 1076: 'Drama',
 1077: 'Comedy',
 1078: 'Comedy',
 1079: 'Comedy',
 1080: 'Comedy',
 1081: 'Comedy',
 1082: 'Drama',
 1083: 'Comedy',
 1084: 'Crime',
 1085: 'Adventure',
 1086: 'Crime',
 1088: 'Drama',
 1089: 'Crime',
 1090: 'Drama',
 1091: 'Comedy',
 1092: 'Crime',
 1093: 'Drama',
 1094: 'Drama',
 1095: 'Drama',
 1096: 'Drama',
 1097: 'Children',
 1099: 'Children',
 1100: 'Action',
 1101: 'Action',
 1103: 'Drama',
 1104: 'Drama',
 1105: 'Horror',
 1107: 'Comedy',
 1111: 'Documentary',
 1112: 'Action',
 1114: 'Crime',
 1116: 'Drama',
 1117: 'Drama',
 1119: 'Drama',
 1120: 'Comedy',
 1121: 'Drama',
 1123: 'Documentary',
 1124: 'Drama',
 1125: 'Comedy',
 1126: 'Comedy',
 1127: 'Action',
 1128: 'Horror',
 1129: 'Action',
 1130: 'Horror',
 1131: 'Drama',
 1132: 'Drama',
 1135: 'Comedy',
 1136: 'Adventure',
 1137: 'Romance',
 1140: 'Drama',
 1144: 'Documentary',
 1147: 'Documentary',
 1148: 'Animation',
 1150: 'Drama',
 1151: 'Animation',
 1156: 'Drama',
 1161: 'Drama',
 1162: 'Comedy',
 1163: 'Drama',
 1167: 'Comedy',
 1170: 'Action',
 1171: 'Comedy',
 1172: 'Drama',
 1173: 'Comedy',
 1175: 'Comedy',
 1176: 'Drama',
 1177: 'Drama',
 1178: 'Drama',
 1179: 'Crime',
 1180: 'Comedy',
 1183: 'Drama',
 1184: 'Comedy',
 1185: 'Drama',
 1186: 'Drama',
 1187: 'Drama',
 1188: 'Comedy',
 1189: 'Documentary',
 1190: 'Crime',
 1191: 'Documentary',
 1192: 'Documentary',
 1193: 'Drama',
 1194: 'Comedy',
 1196: 'Action',
 1197: 'Action',
 1198: 'Action',
 1199: 'Fantasy',
 1200: 'Action',
 1201: 'Action',
 1202: 'Comedy',
 1203: 'Drama',
 1204: 'Adventure',
 1206: 'Crime',
 1207: 'Drama',
 1208: 'Action',
 1209: 'Action',
 1210: 'Action',
 1211: 'Drama',
 1212: 'Film-Noir',
 1213: 'Crime',
 1214: 'Horror',
 1215: 'Action',
 1216: 'Adventure',
 1217: 'Drama',
 1218: 'Action',
 1219: 'Crime',
 1220: 'Action',
 1221: 'Crime',
 1222: 'Drama',
 1223: 'Adventure',
 1224: 'Action',
 1225: 'Drama',
 1226: 'Drama',
 1227: 'Crime',
 1228: 'Drama',
 1230: 'Comedy',
 1231: 'Drama',
 1232: 'Drama',
 1233: 'Action',
 1234: 'Comedy',
 1235: 'Comedy',
 1236: 'Comedy',
 1237: 'Drama',
 1238: 'Comedy',
 1240: 'Action',
 1241: 'Comedy',
 1242: 'Drama',
 1243: 'Comedy',
 1244: 'Comedy',
 1245: 'Crime',
 1246: 'Drama',
 1247: 'Comedy',
 1248: 'Crime',
 1249: 'Action',
 1250: 'Adventure',
 1251: 'Drama',
 1252: 'Crime',
 1253: 'Drama',
 1254: 'Action',
 1255: 'Comedy',
 1256: 'Comedy',
 1257: 'Comedy',
 1258: 'Horror',
 1259: 'Adventure',
 1260: 'Crime',
 1261: 'Action',
 1262: 'Action',
 1263: 'Drama',
 1264: 'Action',
 1265: 'Comedy',
 1266: 'Drama',
 1267: 'Crime',
 1268: 'Comedy',
 1269: 'Comedy',
 1270: 'Adventure',
 1271: 'Comedy',
 1272: 'Drama',
 1273: 'Comedy',
 1274: 'Action',
 1275: 'Action',
 1276: 'Drama',
 1277: 'Comedy',
 1278: 'Comedy',
 1279: 'Comedy',
 1280: 'Drama',
 1281: 'Comedy',
 1282: 'Animation',
 1283: 'Drama',
 1284: 'Crime',
 1285: 'Comedy',
 1286: 'Drama',
 1287: 'Action',
 1288: 'Comedy',
 1289: 'Documentary',
 1290: 'Drama',
 1291: 'Action',
 1292: 'Comedy',
 1293: 'Drama',
 1295: 'Drama',
 1296: 'Drama',
 1297: 'Comedy',
 1298: 'Drama',
 1299: 'Drama',
 1300: 'Comedy',
 1301: 'Drama',
 ...}

In [53]:
items

          id primary_genre
0          1     Adventure
1          2     Adventure
2          3        Comedy
3          4        Comedy
4          5        Comedy
...      ...           ...
9737  193581        Action
9738  193583     Animation
9739  193585         Drama
9740  193587        Action
9741  193609        Comedy

[9742 rows x 2 columns]

In [54]:
all_item_ids = items.id.to_numpy()

als, content_embeddings, item_id_to_row = load_artifacts()
als_model = als["model"]

In [55]:
popularity = interactions.groupby("item_id").size()

normalizes popularity between approximately 0 and 1.

In [56]:
popularity = (popularity / popularity.max()).to_dict()

In [57]:
print(popularity)

{1: 0.6534954407294833, 2: 0.3343465045592705, 3: 0.1580547112462006, 4: 0.02127659574468085, 5: 0.14893617021276595, 6: 0.3100303951367781, 7: 0.1641337386018237, 8: 0.0243161094224924, 9: 0.0486322188449848, 10: 0.4012158054711246, 11: 0.2127659574468085, 12: 0.057750759878419454, 13: 0.0243161094224924, 14: 0.0547112462006079, 15: 0.03951367781155015, 16: 0.24924012158054712, 17: 0.20364741641337386, 18: 0.060790273556231005, 19: 0.2674772036474164, 20: 0.04559270516717325, 21: 0.270516717325228, 22: 0.1094224924012158, 23: 0.0486322188449848, 24: 0.0851063829787234, 25: 0.23100303951367782, 26: 0.03951367781155015, 27: 0.02735562310030395, 28: 0.03343465045592705, 29: 0.11550151975683891, 30: 0.00911854103343465, 31: 0.11550151975683891, 32: 0.5379939209726444, 34: 0.3890577507598784, 36: 0.20364741641337386, 38: 0.0121580547112462, 39: 0.3161094224924012, 40: 0.0060790273556231, 41: 0.04559270516717325, 42: 0.02127659574468085, 43: 0.0243161094224924, 44: 0.1398176291793313, 45: 0.0972644376899696, 46: 0.04559270516717325, 47: 0.6170212765957447, 48: 0.2066869300911854, 49: 0.00303951367781155, 50: 0.6200607902735562, 52: 0.0851063829787234, 53: 0.0060790273556231, 54: 0.00911854103343465, 55: 0.00303951367781155, 57: 0.0243161094224924, 58: 0.11246200607902736, 60: 0.1033434650455927, 61: 0.0182370820668693, 62: 0.24316109422492402, 63: 0.02127659574468085, 64: 0.015197568389057751, 65: 0.09422492401215805, 66: 0.02735562310030395, 68: 0.015197568389057751, 69: 0.060790273556231005, 70: 0.16717325227963525, 71: 0.015197568389057751, 72: 0.02127659574468085, 73: 0.03951367781155015, 74: 0.0243161094224924, 75: 0.015197568389057751, 76: 0.04559270516717325, 77: 0.00303951367781155, 78: 0.00911854103343465, 79: 0.05167173252279635, 80: 0.0060790273556231, 81: 0.0425531914893617, 82: 0.0243161094224924, 83: 0.00303951367781155, 85: 0.02127659574468085, 86: 0.04559270516717325, 87: 0.02127659574468085, 88: 0.0486322188449848, 89: 0.030395136778115502, 92: 0.0243161094224924, 93: 0.02735562310030395, 94: 0.030395136778115502, 95: 0.2553191489361702, 96: 0.00303951367781155, 97: 0.030395136778115502, 99: 0.0060790273556231, 100: 0.0425531914893617, 101: 0.06990881458966565, 102: 0.015197568389057751, 103: 0.00911854103343465, 104: 0.3009118541033435, 105: 0.06990881458966565, 106: 0.00303951367781155, 107: 0.0790273556231003, 108: 0.00303951367781155, 110: 0.7203647416413373, 111: 0.3161094224924012, 112: 0.1398176291793313, 113: 0.00911854103343465, 116: 0.015197568389057751, 117: 0.00303951367781155, 118: 0.0060790273556231, 119: 0.0060790273556231, 121: 0.0060790273556231, 122: 0.0486322188449848, 123: 0.0121580547112462, 125: 0.0364741641337386, 126: 0.02127659574468085, 128: 0.00303951367781155, 129: 0.00303951367781155, 132: 0.0182370820668693, 135: 0.09422492401215805, 137: 0.00303951367781155, 140: 0.0486322188449848, 141: 0.2613981762917933, 144: 0.0364741641337386, 145: 0.15501519756838905, 146: 0.00911854103343465, 147: 0.04559270516717325, 148: 0.00303951367781155, 149: 0.00303951367781155, 150: 0.6109422492401215, 151: 0.1337386018237082, 152: 0.0060790273556231, 153: 0.41641337386018235, 154: 0.0364741641337386, 155: 0.0182370820668693, 156: 0.00911854103343465, 157: 0.03343465045592705, 158: 0.1884498480243161, 159: 0.0425531914893617, 160: 0.17325227963525835, 161: 0.3130699088145897, 162: 0.05167173252279635, 163: 0.2006079027355623, 164: 0.0425531914893617, 165: 0.4376899696048632, 166: 0.00911854103343465, 168: 0.1641337386018237, 169: 0.030395136778115502, 170: 0.10638297872340426, 171: 0.0182370820668693, 172: 0.16109422492401215, 173: 0.1884498480243161, 174: 0.030395136778115502, 175: 0.060790273556231005, 176: 0.03951367781155015, 177: 0.0243161094224924, 178: 0.00303951367781155, 179: 0.0060790273556231, 180: 0.1094224924012158, 181: 0.05167173252279635, 183: 0.0060790273556231, 184: 0.0060790273556231, 185: 0.3404255319148936, 186: 0.1458966565349544, 187: 0.0121580547112462, 188: 0.0364741641337386, 189: 0.00303951367781155, 190: 0.015197568389057751, 191: 0.0182370820668693, 193: 0.10638297872340426, 194: 0.0547112462006079, 195: 0.030395136778115502, 196: 0.13677811550151975, 198: 0.0851063829787234, 199: 0.0121580547112462, 201: 0.00303951367781155, 202: 0.00303951367781155, 203: 0.0668693009118541, 204: 0.0911854103343465, 205: 0.02735562310030395, 206: 0.0060790273556231, 207: 0.06382978723404255, 208: 0.3495440729483283, 209: 0.00911854103343465, 210: 0.0121580547112462, 211: 0.0060790273556231, 212: 0.00911854103343465, 213: 0.0182370820668693, 214: 0.0060790273556231, 215: 0.0729483282674772, 216: 0.14893617021276595, 217: 0.0182370820668693, 218: 0.0425531914893617, 219: 0.00303951367781155, 220: 0.00303951367781155, 222: 0.0486322188449848, 223: 0.3161094224924012, 224: 0.12158054711246201, 225: 0.1580547112462006, 227: 0.0668693009118541, 228: 0.00911854103343465, 229: 0.02127659574468085, 230: 0.0729483282674772, 231: 0.40425531914893614, 232: 0.0425531914893617, 233: 0.0364741641337386, 234: 0.05167173252279635, 235: 0.2127659574468085, 236: 0.13677811550151975, 237: 0.0668693009118541, 238: 0.0060790273556231, 239: 0.05167173252279635, 240: 0.0121580547112462, 241: 0.00303951367781155, 242: 0.015197568389057751, 243: 0.00303951367781155, 246: 0.08814589665653495, 247: 0.06382978723404255, 248: 0.05167173252279635, 249: 0.0547112462006079, 250: 0.0182370820668693, 251: 0.00911854103343465, 252: 0.13069908814589665, 253: 0.331306990881459, 254: 0.00303951367781155, 255: 0.02127659574468085, 256: 0.10638297872340426, 257: 0.0425531914893617, 258: 0.030395136778115502, 259: 0.015197568389057751, 260: 0.7629179331306991, 261: 0.1276595744680851, 262: 0.06382978723404255, 263: 0.00303951367781155, 265: 0.10030395136778116, 266: 0.2066869300911854, 267: 0.05167173252279635, 269: 0.0060790273556231, 270: 0.015197568389057751, 271: 0.0121580547112462, 272: 0.09422492401215805, 273: 0.0851063829787234, 274: 0.02127659574468085, 275: 0.0182370820668693, 276: 0.0668693009118541, 277: 0.11550151975683891, 278: 0.0060790273556231, 279: 0.0060790273556231, 280: 0.03951367781155015, 281: 0.0425531914893617, 282: 0.12158054711246201, 283: 0.00911854103343465, 284: 0.00303951367781155, 285: 0.00303951367781155, 287: 0.00303951367781155, 288: 0.2796352583586626, 289: 0.0243161094224924, 290: 0.0425531914893617, 291: 0.00911854103343465, 292: 0.3069908814589666, 293: 0.40425531914893614, 294: 0.0060790273556231, 295: 0.00303951367781155, 296: 0.9331306990881459, 298: 0.00303951367781155, 299: 0.0121580547112462, 300: 0.24620060790273557, 301: 0.00303951367781155, 302: 0.015197568389057751, 303: 0.0972644376899696, 304: 0.00911854103343465, 305: 0.02735562310030395, 306: 0.0486322188449848, 307: 0.0729483282674772, 308: 0.060790273556231005, 310: 0.00303951367781155, 311: 0.00303951367781155, 312: 0.02735562310030395, 313: 0.00911854103343465, 314: 0.0486322188449848, 315: 0.11550151975683891, 316: 0.425531914893617, 317: 0.24620060790273557, 318: 0.9635258358662614, 319: 0.060790273556231005, 320: 0.00303951367781155, 321: 0.0060790273556231, 322: 0.030395136778115502, 324: 0.00303951367781155, 325: 0.02127659574468085, 326: 0.00911854103343465, 327: 0.1033434650455927, 328: 0.030395136778115502, 329: 0.3282674772036474, 330: 0.0182370820668693, 331: 0.0060790273556231, 332: 0.0364741641337386, 333: 0.1519756838905775, 334: 0.015197568389057751, 335: 0.0060790273556231, 336: 0.00303951367781155, 337: 0.23404255319148937, 338: 0.057750759878419454, 339: 0.2978723404255319, 340: 0.015197568389057751, 341: 0.0060790273556231, 342: 0.10030395136778116, 343: 0.015197568389057751, 344: 0.48936170212765956, 345: 0.1094224924012158, 346: 0.0182370820668693, 347: 0.0182370820668693, 348: 0.0911854103343465, 349: 0.3343465045592705, 350: 0.17325227963525835, 351: 0.05167173252279635, 352: 0.0060790273556231, 353: 0.1945288753799392, 354: 0.0182370820668693, 355: 0.1276595744680851, 356: 1.0, 357: 0.3130699088145897, 358: 0.02735562310030395, 359: 0.00303951367781155, 360: 0.0243161094224924, 361: 0.05167173252279635, 362: 0.1033434650455927, 363: 0.0060790273556231, 364: 0.5227963525835866, 365: 0.0121580547112462, 366: 0.0364741641337386, 367: 0.47720364741641336, 368: 0.22492401215805471, 369: 0.0060790273556231, 370: 0.1762917933130699, 371: 0.06382978723404255, 372: 0.06382978723404255, 373: 0.03343465045592705, 374: 0.07598784194528875, 376: 0.12158054711246201, 377: 0.5197568389057751, 378: 0.02127659574468085, 379: 0.06382978723404255, 380: 0.541033434650456, 381: 0.03343465045592705, 382: 0.0486322188449848, 383: 0.06382978723404255, 384: 0.0060790273556231, 385: 0.00303951367781155, 386: 0.00303951367781155, 387: 0.0121580547112462, 388: 0.0060790273556231, 389: 0.0060790273556231, 390: 0.015197568389057751, 391: 0.00303951367781155, 393: 0.030395136778115502, 405: 0.0364741641337386, 406: 0.00303951367781155, 407: 0.0243161094224924, 408: 0.0060790273556231, 409: 0.00303951367781155, 410: 0.2553191489361702, 412: 0.04559270516717325, 413: 0.0790273556231003, 414: 0.0182370820668693, 415: 0.0486322188449848, 416: 0.0243161094224924, 417: 0.03951367781155015, 418: 0.0060790273556231, 419: 0.060790273556231005, 420: 0.17933130699088146, 421: 0.0364741641337386, 422: 0.015197568389057751, 423: 0.030395136778115502, 424: 0.00911854103343465, 425: 0.0060790273556231, 426: 0.02127659574468085, 427: 0.0364741641337386, 428: 0.0547112462006079, 429: 0.0182370820668693, 430: 0.0060790273556231, 431: 0.1276595744680851, 432: 0.16717325227963525, 433: 0.0243161094224924, 434: 0.3069908814589666, 435: 0.19148936170212766, 436: 0.02127659574468085, 437: 0.02735562310030395, 438: 0.02127659574468085, 440: 0.23100303951367782, 441: 0.1276595744680851, 442: 0.24620060790273557, 444: 0.0182370820668693, 445: 0.0364741641337386, 446: 0.02735562310030395, 448: 0.0243161094224924, 449: 0.00303951367781155, 450: 0.02127659574468085, 451: 0.00303951367781155, 452: 0.00911854103343465, 453: 0.015197568389057751, 454: 0.3069908814589666, 455: 0.11246200607902736, 456: 0.0121580547112462, 457: 0.5775075987841946, 458: 0.015197568389057751, 459: 0.0182370820668693, 460: 0.00911854103343465, 461: 0.0121580547112462, 464: 0.030395136778115502, 466: 0.182370820668693, 467: 0.00303951367781155, 468: 0.0668693009118541, 469: 0.015197568389057751, 470: 0.00303951367781155, 471: 0.12158054711246201, 472: 0.0182370820668693, 473: 0.02127659574468085, 474: 0.2127659574468085, 475: 0.07598784194528875, 476: 0.00303951367781155, 477: 0.05167173252279635, 478: 0.00303951367781155, 479: 0.0121580547112462, 480: 0.723404255319149, 481: 0.057750759878419454, 482: 0.0243161094224924, 484: 0.0060790273556231, 485: 0.16109422492401215, 486: 0.00911854103343465, 487: 0.0121580547112462, 488: 0.00303951367781155, 489: 0.03343465045592705, 490: 0.0364741641337386, 491: 0.05167173252279635, 492: 0.0425531914893617, 493: 0.0364741641337386, 494: 0.12462006079027356, 495: 0.00303951367781155, 496: 0.00303951367781155, 497: 0.13069908814589665, 499: 0.0060790273556231, 500: 0.4376899696048632, 501: 0.0182370820668693, 502: 0.04559270516717325, 504: 0.0060790273556231, 505: 0.02127659574468085, 506: 0.0060790273556231, 507: 0.03951367781155015, 508: 0.2006079027355623, 509: 0.18541033434650456, 510: 0.00303951367781155, 511: 0.0060790273556231, 512: 0.0121580547112462, 513: 0.0121580547112462, 514: 0.0547112462006079, 515: 0.0729483282674772, 516: 0.0547112462006079, 517: 0.02735562310030395, 518: 0.0121580547112462, 519: 0.06382978723404255, 520: 0.20972644376899696, 521: 0.00911854103343465, 522: 0.02127659574468085, 523: 0.0121580547112462, 524: 0.1033434650455927, 526: 0.00303951367781155, 527: 0.668693009118541, 528: 0.00911854103343465, 529: 0.12158054711246201, 531: 0.0729483282674772, 532: 0.0486322188449848, 533: 0.0547112462006079, 534: 0.0425531914893617, 535: 0.04559270516717325, 536: 0.00911854103343465, 537: 0.0364741641337386, 538: 0.0364741641337386, 539: 0.3221884498480243, 540: 0.0547112462006079, 541: 0.3768996960486322, 542: 0.0425531914893617, 543: 0.12462006079027356, 544: 0.0243161094224924, 546: 0.06382978723404255, 547: 0.0060790273556231, 548: 0.0182370820668693, 549: 0.0060790273556231, 550: 0.015197568389057751, 551: 0.2826747720364742, 552: 0.18541033434650456, 553: 0.19756838905775076, 555: 0.19756838905775076, 556: 0.0182370820668693, 558: 0.0243161094224924, 562: 0.06990881458966565, 563: 0.00303951367781155, 564: 0.0060790273556231, 567: 0.00911854103343465, 568: 0.0060790273556231, 569: 0.0182370820668693, 573: 0.00303951367781155, 574: 0.0121580547112462, 575: 0.0486322188449848, 577: 0.0121580547112462, 579: 0.00303951367781155, 580: 0.015197568389057751, 581: 0.0121580547112462, 583: 0.00303951367781155, 585: 0.1094224924012158, 586: 0.3525835866261398, 587: 0.3495440729483283, 588: 0.5562310030395137, 589: 0.6808510638297872, 590: 0.49848024316109424, 592: 0.574468085106383, 593: 0.8480243161094225, 594: 0.23404255319148937, 595: 0.44376899696048633, 596: 0.182370820668693, 597: 0.41033434650455924, 599: 0.03343465045592705, 600: 0.00303951367781155, 602: 0.00303951367781155, 605: 0.030395136778115502, 606: 0.0121580547112462, 608: 0.5501519756838906, 609: 0.0425531914893617, 610: 0.10030395136778116, 611: 0.0182370820668693, 612: 0.0182370820668693, 613: 0.0243161094224924, 615: 0.00303951367781155, 616: 0.13677811550151975, 617: 0.00911854103343465, 618: 0.00303951367781155, 619: 0.015197568389057751, 626: 0.00303951367781155, 627: 0.0182370820668693, 628: 0.10638297872340426, 631: 0.03343465045592705, 632: 0.00303951367781155, 633: 0.00303951367781155, 634: 0.0121580547112462, 635: 0.0060790273556231, 636: 0.00303951367781155, 637: 0.10030395136778116, 638: 0.00303951367781155, 639: 0.0121580547112462, 640: 0.03343465045592705, 645: 0.0060790273556231, 647: 0.08814589665653495, 648: 0.49240121580547114, 649: 0.00303951367781155, 650: 0.0121580547112462, 653: 0.19756838905775076, 656: 0.015197568389057751, 661: 0.14893617021276595, 662: 0.02127659574468085, 663: 0.0364741641337386, 665: 0.00911854103343465, 667: 0.0243161094224924, 668: 0.0060790273556231, 670: 0.0060790273556231, 671: 0.1094224924012158, 673: 0.16109422492401215, 674: 0.02735562310030395, 678: 0.02735562310030395, 679: 0.00303951367781155, 680: 0.0121580547112462, 685: 0.0060790273556231, 688: 0.02735562310030395, 691: 0.00911854103343465, 692: 0.0121580547112462, 694: 0.03343465045592705, 695: 0.0060790273556231, 697: 0.015197568389057751, 698: 0.00303951367781155, 700: 0.02127659574468085, 703: 0.0060790273556231, 704: 0.02127659574468085, 706: 0.00303951367781155, 707: 0.06382978723404255, 708: 0.1762917933130699, 709: 0.03343465045592705, 710: 0.0243161094224924, 711: 0.030395136778115502, 714: 0.04559270516717325, 715: 0.00911854103343465, 718: 0.0121580547112462, 719: 0.10638297872340426, 720: 0.08206686930091185, 722: 0.00303951367781155, 724: 0.09422492401215805, 725: 0.015197568389057751, 726: 0.00303951367781155, 728: 0.030395136778115502, 731: 0.00911854103343465, 733: 0.3677811550151976, 735: 0.02127659574468085, 736: 0.3738601823708207, 737: 0.060790273556231005, 741: 0.08206686930091185, 742: 0.03343465045592705, 743: 0.08814589665653495, 745: 0.1458966565349544, 747: 0.00911854103343465, 748: 0.0668693009118541, 750: 0.2948328267477204, 757: 0.00303951367781155, 759: 0.0060790273556231, 760: 0.0060790273556231, 761: 0.057750759878419454, 762: 0.12462006079027356, 764: 0.0060790273556231, 765: 0.057750759878419454, 766: 0.0121580547112462, 773: 0.00303951367781155, 775: 0.00303951367781155, 778: 0.3100303951367781, 779: 0.0060790273556231, 780: 0.6139817629179332, 781: 0.02127659574468085, 782: 0.0243161094224924, 783: 0.14285714285714285, 784: 0.1641337386018237, 785: 0.1276595744680851, 786: 0.1945288753799392, 788: 0.24924012158054712, 790: 0.00303951367781155, 791: 0.00303951367781155, 795: 0.0060790273556231, 798: 0.0364741641337386, 799: 0.06990881458966565, 800: 0.057750759878419454, 801: 0.03343465045592705, 802: 0.1398176291793313, 803: 0.00303951367781155, 804: 0.0243161094224924, 805: 0.10638297872340426, 806: 0.00303951367781155, 808: 0.0060790273556231, 809: 0.02735562310030395, 810: 0.0364741641337386, 813: 0.015197568389057751, 818: 0.030395136778115502, 823: 0.00303951367781155, 824: 0.00303951367781155, 828: 0.0182370820668693, 829: 0.02735562310030395, 830: 0.06382978723404255, 832: 0.11246200607902736, 833: 0.0182370820668693, 835: 0.00911854103343465, 836: 0.05167173252279635, 837: 0.10030395136778116, 838: 0.0911854103343465, 839: 0.04559270516717325, 840: 0.0121580547112462, 841: 0.0060790273556231, 842: 0.0364741641337386, 848: 0.02127659574468085, 849: 0.1337386018237082, 851: 0.0182370820668693, 852: 0.13069908814589665, 858: 0.5835866261398176, 861: 0.02735562310030395, 866: 0.06990881458966565, 867: 0.0060790273556231, 869: 0.00911854103343465, 870: 0.0060790273556231, 875: 0.00303951367781155, 876: 0.00303951367781155, 879: 0.0121580547112462, 880: 0.08206686930091185, 881: 0.015197568389057751, 882: 0.00303951367781155, 885: 0.0060790273556231, 886: 0.0182370820668693, 888: 0.00911854103343465, 889: 0.00303951367781155, 891: 0.015197568389057751, 892: 0.03951367781155015, 893: 0.00911854103343465, 896: 0.0060790273556231, 897: 0.0060790273556231, 898: 0.08814589665653495, 899: 0.14285714285714285, 900: 0.0364741641337386, 901: 0.02127659574468085, 902: 0.1094224924012158, 903: 0.182370820668693, 904: 0.2553191489361702, 905: 0.0425531914893617, 906: 0.02127659574468085, 907: 0.0060790273556231, 908: 0.17325227963525835, 909: 0.08206686930091185, 910: 0.1519756838905775, 911: 0.03951367781155015, 912: 0.303951367781155, 913: 0.1337386018237082, 914: 0.10638297872340426, 915: 0.0911854103343465, 916: 0.0790273556231003, 917: 0.0060790273556231, 918: 0.030395136778115502, 919: 0.2796352583586626, 920: 0.13677811550151975, 921: 0.02735562310030395, 922: 0.08206686930091185, 923: 0.20972644376899696, 924: 0.331306990881459, 926: 0.0729483282674772, 927: 0.00911854103343465, 928: 0.0547112462006079, 929: 0.00303951367781155, 930: 0.060790273556231005, 931: 0.02735562310030395, 932: 0.0243161094224924, 933: 0.06990881458966565, 934: 0.0364741641337386, 935: 0.00911854103343465, 936: 0.0182370820668693, 937: 0.0060790273556231, 938: 0.0182370820668693, 940: 0.0243161094224924, 941: 0.0060790273556231, 942: 0.0182370820668693, 943: 0.02127659574468085, 944: 0.00911854103343465, 945: 0.02127659574468085, 946: 0.00911854103343465, 947: 0.0121580547112462, 948: 0.0182370820668693, 949: 0.0182370820668693, 950: 0.02127659574468085, 951: 0.0425531914893617, 952: 0.0364741641337386, 953: 0.1762917933130699, 954: 0.0547112462006079, 955: 0.0547112462006079, 956: 0.00303951367781155, 959: 0.00303951367781155, 961: 0.00303951367781155, 963: 0.00303951367781155, 965: 0.03343465045592705, 968: 0.0851063829787234, 969: 0.1033434650455927, 970: 0.00303951367781155, 971: 0.030395136778115502, 973: 0.015197568389057751, 976: 0.00303951367781155, 979: 0.00303951367781155, 981: 0.0060790273556231, 982: 0.00303951367781155, 984: 0.0060790273556231, 986: 0.03951367781155015, 987: 0.00303951367781155, 988: 0.0060790273556231, 990: 0.015197568389057751, 991: 0.03343465045592705, 993: 0.00303951367781155, 994: 0.03343465045592705, 996: 0.03951367781155015, 998: 0.00911854103343465, 999: 0.0364741641337386, 1003: 0.00911854103343465, 1004: 0.0182370820668693, 1005: 0.0243161094224924, 1006: 0.015197568389057751, 1007: 0.030395136778115502, 1008: 0.00303951367781155, 1009: 0.02735562310030395, 1010: 0.02735562310030395, 1011: 0.0243161094224924, 1012: 0.02735562310030395, 1013: 0.0364741641337386, 1014: 0.015197568389057751, 1015: 0.060790273556231005, 1016: 0.015197568389057751, 1017: 0.030395136778115502, 1018: 0.0182370820668693, 1019: 0.05167173252279635, 1020: 0.11246200607902736, 1021: 0.08206686930091185, 1022: 0.1276595744680851, 1023: 0.03951367781155015, 1024: 0.0182370820668693, 1025: 0.07598784194528875, 1027: 0.0851

In [58]:
rows = []
user_counts = interactions.groupby("user_id").size()
eligible_users = user_counts[user_counts >= MIN_RATINGS_PER_USER].index

In [59]:
print(f"Building ranking dataset for {len(eligible_users)} eligible users...")
for user_id in eligible_users:
  user_rows = interactions[interactions.user_id == user_id]
  positive_ids = set(user_rows[user_rows.rating >= 4].item_id)
  if not positive_ids:
    continue
  all_seen = set(user_rows.item_id)
  liked_rows = [item_id_to_row[i] for i in positive_ids if i in item_id_to_row]
  if not liked_rows:
    continue
  user_taste_vec = content_embeddings[liked_rows].mean(axis=0)
  user_taste_vec = user_taste_vec / (np.linalg.norm(user_taste_vec) + 1e-8)

  als_user_idx = als["user_id_to_idx"].get(user_id)
  unseen = np.setdiff1d(all_item_ids, np.array(list(all_seen)), assume_unique=False)
  n_neg = min(len(unseen), len(positive_ids) * NEGATIVES_PER_USER_MULTIPLIER)
  if n_neg == 0:
      continue
  weights = np.array([popularity.get(i, 0.001) for i in unseen])
  weights = weights / weights.sum()
  negative_ids = np.random.choice(unseen, size=n_neg, replace=False, p=weights)

  candidates = list(positive_ids) + list(negative_ids)
  labels = [1] * len(positive_ids) + [0] * len(negative_ids)

  for item_id, label in zip(candidates, labels):
      als_score = 0.0
      if als_user_idx is not None and item_id in als["item_id_to_idx"]:
          item_idx = als["item_id_to_idx"][item_id]
          als_score = float(
              np.dot(als_model.user_factors[als_user_idx], als_model.item_factors[item_idx])
          )

      content_sim = 0.0
      if item_id in item_id_to_row:
          item_vec = content_embeddings[item_id_to_row[item_id]]
          item_vec = item_vec / (np.linalg.norm(item_vec) + 1e-8)
          content_sim = float(np.dot(user_taste_vec, item_vec))

      genre = item_genre.get(item_id, "Unknown")
      user_genres = {item_genre.get(i, "Unknown") for i in positive_ids}
      genre_match = 1.0 if genre in user_genres else 0.0

      rows.append({
          "user_id": user_id,
          "item_id": item_id,
          "als_score": als_score,
          "content_sim": content_sim,
          "popularity": popularity.get(item_id, 0.0),
          "genre_match": genre_match,
          "label": label,
      })

Building ranking dataset for 610 eligible users...

In [60]:
df = pd.DataFrame(rows)
    # lambdarank requires rows grouped contiguously by user_id
df = df.sort_values("user_id").reset_index(drop=True)

out_path = os.path.join(MODELS_DIR, "ranking_train.csv")
df.to_csv(out_path, index=False)
print(f"Saved {len(df)} training rows ({df.label.sum()} positive) to {out_path}")

Saved 145740 training rows (48580 positive) to ./models/ranking_train.csv

Training the Learning-to-Rank Model with LightGBM

In [61]:
import lightgbm as lgb
from sklearn.model_selection import GroupShuffleSplit

In [62]:
FEATURE_COLS = ["als_score", "content_sim", "popularity", "genre_match"]

In [63]:
df = pd.read_csv(os.path.join(MODELS_DIR, "ranking_train.csv"))

In [64]:
df.head()

   user_id  item_id  als_score  content_sim  popularity  genre_match  label
0        1     1024   0.358048     0.492888    0.018237          1.0      1
1        1    45720  -0.015160     0.599470    0.103343          1.0      0
2        1     3107   0.152455     0.653912    0.069909          1.0      0
3        1   102742   0.010390     0.404498    0.003040          0.0      0
4        1    44199   0.114459     0.617456    0.121581          1.0      0

In [65]:
splitter = GroupShuffleSplit(test_size=0.2, n_splits=1, random_state=42)
train_idx, val_idx = next(splitter.split(df, groups=df.user_id))
train_df = df.iloc[train_idx].sort_values("user_id")
val_df = df.iloc[val_idx].sort_values("user_id")

train_group = train_df.groupby("user_id").size().to_numpy()
val_group = val_df.groupby("user_id").size().to_numpy()

train_set = lgb.Dataset(train_df[FEATURE_COLS], label=train_df["label"], group=train_group)
val_set = lgb.Dataset(val_df[FEATURE_COLS], label=val_df["label"], group=val_group, reference=train_set)

In [73]:
print("train rows", len(train_df), "train users", train_df.user_id.nunique())
print("val rows", len(val_df), "val users", val_df.user_id.nunique())
print("train label balance", train_df.label.value_counts().to_dict())
print("val label balance", val_df.label.value_counts().to_dict())
print("val group sizes", val_df.groupby("user_id").size().describe())

train rows 114648 train users 487
val rows 31092 val users 122
train label balance {0: 76432, 1: 38216}
val label balance {0: 20728, 1: 10364}
val group sizes count     122.000000
mean      254.852459
std       327.234055
min         9.000000
25%        63.000000
50%       117.000000
75%       327.000000
max      1839.000000
dtype: float64

In [66]:
params = {
        "objective": "lambdarank",
        "metric": "ndcg",
        "ndcg_eval_at": [5, 10],
        "learning_rate": 0.05,
        "num_leaves": 15,
        "min_data_in_leaf": 10,
        "verbose": -1,
    }

In [67]:
import json

In [74]:
eval_results = {}

print("Training LightGBM ranker...")
ranker = lgb.train(
    params,
    train_set,
    num_boost_round=200,
    valid_sets=[val_set],
    callbacks=[
        lgb.early_stopping(stopping_rounds=50),
        lgb.log_evaluation(1),                    # print every round
        lgb.record_evaluation(eval_results),       # capture the curve for inspection
    ],
)

out_path = os.path.join(MODELS_DIR, "ranker.txt")
ranker.save_model(out_path)
print("best_iteration:", ranker.best_iteration)
print("val ndcg@10 curve (first 15 rounds):", eval_results["valid_0"]["ndcg@10"][:15])

Training LightGBM ranker...
[1]	valid_0's ndcg@5: 0.980463	valid_0's ndcg@10: 0.976159
Training until validation scores don't improve for 50 rounds
[2]	valid_0's ndcg@5: 0.986783	valid_0's ndcg@10: 0.977583
[3]	valid_0's ndcg@5: 0.985708	valid_0's ndcg@10: 0.97676
[4]	valid_0's ndcg@5: 0.984633	valid_0's ndcg@10: 0.974958
[5]	valid_0's ndcg@5: 0.98583	valid_0's ndcg@10: 0.975497
[6]	valid_0's ndcg@5: 0.98583	valid_0's ndcg@10: 0.976013
[7]	valid_0's ndcg@5: 0.984754	valid_0's ndcg@10: 0.974722
[8]	valid_0's ndcg@5: 0.985952	valid_0's ndcg@10: 0.975462
[9]	valid_0's ndcg@5: 0.98722	valid_0's ndcg@10: 0.975174
[10]	valid_0's ndcg@5: 0.986144	valid_0's ndcg@10: 0.973537
[11]	valid_0's ndcg@5: 0.984947	valid_0's ndcg@10: 0.973925
[12]	valid_0's ndcg@5: 0.986023	valid_0's ndcg@10: 0.973478
[13]	valid_0's ndcg@5: 0.986387	valid_0's ndcg@10: 0.973682
[14]	valid_0's ndcg@5: 0.986387	valid_0's ndcg@10: 0.974239
[15]	valid_0's ndcg@5: 0.983557	valid_0's ndcg@10: 0.974632
[16]	valid_0's ndcg@5: 0.985626	valid_0's ndcg@10: 0.975446
[17]	valid_0's ndcg@5: 0.985311	valid_0's ndcg@10: 0.974146
[18]	valid_0's ndcg@5: 0.985675	valid_0's ndcg@10: 0.975523
[19]	valid_0's ndcg@5: 0.985482	valid_0's ndcg@10: 0.975489
[20]	valid_0's ndcg@5: 0.98599	valid_0's ndcg@10: 0.974184
[21]	valid_0's ndcg@5: 0.987065	valid_0's ndcg@10: 0.974277
[22]	valid_0's ndcg@5: 0.987065	valid_0's ndcg@10: 0.974309
[23]	valid_0's ndcg@5: 0.987065	valid_0's ndcg@10: 0.973809
[24]	valid_0's ndcg@5: 0.987065	valid_0's ndcg@10: 0.974873
[25]	valid_0's ndcg@5: 0.987258	valid_0's ndcg@10: 0.974511
[26]	valid_0's ndcg@5: 0.98611	valid_0's ndcg@10: 0.972719
[27]	valid_0's ndcg@5: 0.985917	valid_0's ndcg@10: 0.973169
[28]	valid_0's ndcg@5: 0.987429	valid_0's ndcg@10: 0.973539
[29]	valid_0's ndcg@5: 0.98958	valid_0's ndcg@10: 0.974198
[30]	valid_0's ndcg@5: 0.98958	valid_0's ndcg@10: 0.974719
[31]	valid_0's ndcg@5: 0.99097	valid_0's ndcg@10: 0.976184
[32]	valid_0's ndcg@5: 0.99097	valid_0's ndcg@10: 0.976231
[33]	valid_0's ndcg@5: 0.99097	valid_0's ndcg@10: 0.976231
[34]	valid_0's ndcg@5: 0.99097	valid_0's ndcg@10: 0.977221
[35]	valid_0's ndcg@5: 0.992238	valid_0's ndcg@10: 0.977427
[36]	valid_0's ndcg@5: 0.992238	valid_0's ndcg@10: 0.977427
[37]	valid_0's ndcg@5: 0.992238	valid_0's ndcg@10: 0.977939
[38]	valid_0's ndcg@5: 0.992238	valid_0's ndcg@10: 0.977907
[39]	valid_0's ndcg@5: 0.992238	valid_0's ndcg@10: 0.977948
[40]	valid_0's ndcg@5: 0.992238	valid_0's ndcg@10: 0.977974
[41]	valid_0's ndcg@5: 0.992238	valid_0's ndcg@10: 0.978517
[42]	valid_0's ndcg@5: 0.992238	valid_0's ndcg@10: 0.978543
[43]	valid_0's ndcg@5: 0.990848	valid_0's ndcg@10: 0.97822
[44]	valid_0's ndcg@5: 0.990848	valid_0's ndcg@10: 0.978206
[45]	valid_0's ndcg@5: 0.990848	valid_0's ndcg@10: 0.979274
[46]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.979479
[47]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.978983
[48]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.979446
[49]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.981046
[50]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.981024
[51]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.981652
[52]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.981773
[53]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.981805
[54]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.98237
[55]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.981859
[56]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.981879
[57]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.9824
[58]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.982343
[59]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.982428
[60]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.982428
[61]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.981906
[62]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.98196
[63]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.982003
[64]	valid_0's ndcg@5: 0.992045	valid_0's ndcg@10: 0.983046
[65]	valid_0's ndcg@5: 0.992167	valid_0's ndcg@10: 0.982582
[66]	valid_0's ndcg@5: 0.992167	valid_0's ndcg@10: 0.982604
[67]	valid_0's ndcg@5: 0.992167	valid_0's ndcg@10: 0.982563
[68]	valid_0's ndcg@5: 0.992167	valid_0's ndcg@10: 0.983052
[69]	valid_0's ndcg@5: 0.992167	valid_0's ndcg@10: 0.983073
[70]	valid_0's ndcg@5: 0.99305	valid_0's ndcg@10: 0.983593
[71]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.983193
[72]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.98326
[73]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.983251
[74]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.983256
[75]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.983256
[76]	valid_0's ndcg@5: 0.99305	valid_0's ndcg@10: 0.984195
[77]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.983788
[78]	valid_0's ndcg@5: 0.99305	valid_0's ndcg@10: 0.983663
[79]	valid_0's ndcg@5: 0.99305	valid_0's ndcg@10: 0.984206
[80]	valid_0's ndcg@5: 0.99305	valid_0's ndcg@10: 0.984185
[81]	valid_0's ndcg@5: 0.99305	valid_0's ndcg@10: 0.984228
[82]	valid_0's ndcg@5: 0.99305	valid_0's ndcg@10: 0.984749
[83]	valid_0's ndcg@5: 0.99305	valid_0's ndcg@10: 0.984791
[84]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.984394
[85]	valid_0's ndcg@5: 0.99305	valid_0's ndcg@10: 0.984791
[86]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.98442
[87]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.98442
[88]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.98442
[89]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.984425
[90]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.984468
[91]	valid_0's ndcg@5: 0.993243	valid_0's ndcg@10: 0.983903
[92]	valid_0's ndcg@5: 0.994269	valid_0's ndcg@10: 0.98461
[93]	valid_0's ndcg@5: 0.994269	valid_0's ndcg@10: 0.985106
[94]	valid_0's ndcg@5: 0.994269	valid_0's ndcg@10: 0.985106
[95]	valid_0's ndcg@5: 0.994269	valid_0's ndcg@10: 0.984558
[96]	valid_0's ndcg@5: 0.994269	valid_0's ndcg@10: 0.984558
[97]	valid_0's ndcg@5: 0.994269	valid_0's ndcg@10: 0.98508
[98]	valid_0's ndcg@5: 0.994269	valid_0's ndcg@10: 0.98508
[99]	valid_0's ndcg@5: 0.994633	valid_0's ndcg@10: 0.985294
[100]	valid_0's ndcg@5: 0.994633	valid_0's ndcg@10: 0.984773
[101]	valid_0's ndcg@5: 0.994633	valid_0's ndcg@10: 0.984725
[102]	valid_0's ndcg@5: 0.994633	valid_0's ndcg@10: 0.984747
[103]	valid_0's ndcg@5: 0.994633	valid_0's ndcg@10: 0.98579
[104]	valid_0's ndcg@5: 0.994633	valid_0's ndcg@10: 0.985811
[105]	valid_0's ndcg@5: 0.994633	valid_0's ndcg@10: 0.985811
[106]	valid_0's ndcg@5: 0.994633	valid_0's ndcg@10: 0.98577
[107]	valid_0's ndcg@5: 0.994633	valid_0's ndcg@10: 0.98577
[108]	valid_0's ndcg@5: 0.994633	valid_0's ndcg@10: 0.98577
[109]	valid_0's ndcg@5: 0.99444	valid_0's ndcg@10: 0.985645
[110]	valid_0's ndcg@5: 0.993365	valid_0's ndcg@10: 0.98559
[111]	valid_0's ndcg@5: 0.993365	valid_0's ndcg@10: 0.985557
[112]	valid_0's ndcg@5: 0.993365	valid_0's ndcg@10: 0.985521
[113]	valid_0's ndcg@5: 0.993001	valid_0's ndcg@10: 0.985263
[114]	valid_0's ndcg@5: 0.993001	valid_0's ndcg@10: 0.985763
[115]	valid_0's ndcg@5: 0.993001	valid_0's ndcg@10: 0.985722
[116]	valid_0's ndcg@5: 0.993193	valid_0's ndcg@10: 0.98639
[117]	valid_0's ndcg@5: 0.993193	valid_0's ndcg@10: 0.98639
[118]	valid_0's ndcg@5: 0.993193	valid_0's ndcg@10: 0.986411
[119]	valid_0's ndcg@5: 0.993193	valid_0's ndcg@10: 0.986411
[120]	valid_0's ndcg@5: 0.993193	valid_0's ndcg@10: 0.986411
[121]	valid_0's ndcg@5: 0.993193	valid_0's ndcg@10: 0.986411
[122]	valid_0's ndcg@5: 0.993557	valid_0's ndcg@10: 0.98668
[123]	valid_0's ndcg@5: 0.993071	valid_0's ndcg@10: 0.986365
[124]	valid_0's ndcg@5: 0.993557	valid_0's ndcg@10: 0.98668
[125]	valid_0's ndcg@5: 0.994583	valid_0's ndcg@10: 0.987313
[126]	valid_0's ndcg@5: 0.994825	valid_0's ndcg@10: 0.987471
[127]	valid_0's ndcg@5: 0.994825	valid_0's ndcg@10: 0.988061
[128]	valid_0's ndcg@5: 0.994825	valid_0's ndcg@10: 0.988561
[129]	valid_0's ndcg@5: 0.994461	valid_0's ndcg@10: 0.987782
[130]	valid_0's ndcg@5: 0.994461	valid_0's ndcg@10: 0.988325
[131]	valid_0's ndcg@5: 0.994461	valid_0's ndcg@10: 0.988305
[132]	valid_0's ndcg@5: 0.994825	valid_0's ndcg@10: 0.988541
[133]	valid_0's ndcg@5: 0.994461	valid_0's ndcg@10: 0.988337
[134]	valid_0's ndcg@5: 0.994461	valid_0's ndcg@10: 0.987753
[135]	valid_0's ndcg@5: 0.994461	valid_0's ndcg@10: 0.987232
[136]	valid_0's ndcg@5: 0.994461	valid_0's ndcg@10: 0.987253
[137]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.98796
[138]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.987413
[139]	valid_0's ndcg@5: 0.994461	valid_0's ndcg@10: 0.986732
[140]	valid_0's ndcg@5: 0.994825	valid_0's ndcg@10: 0.986968
[141]	valid_0's ndcg@5: 0.994825	valid_0's ndcg@10: 0.986946
[142]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.986939
[143]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.986939
[144]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.98696
[145]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.986939
[146]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.986939
[147]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.986939
[148]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.986917
[149]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.987439
[150]	valid_0's ndcg@5: 0.99375	valid_0's ndcg@10: 0.987439
[151]	valid_0's ndcg@5: 0.992311	valid_0's ndcg@10: 0.987669
[152]	valid_0's ndcg@5: 0.993386	valid_0's ndcg@10: 0.987724
[153]	valid_0's ndcg@5: 0.992311	valid_0's ndcg@10: 0.987669
[154]	valid_0's ndcg@5: 0.992311	valid_0's ndcg@10: 0.987695
[155]	valid_0's ndcg@5: 0.992311	valid_0's ndcg@10: 0.987695
[156]	valid_0's ndcg@5: 0.992311	valid_0's ndcg@10: 0.987695
[157]	valid_0's ndcg@5: 0.992311	valid_0's ndcg@10: 0.987695
[158]	valid_0's ndcg@5: 0.992311	valid_0's ndcg@10: 0.987695
[159]	valid_0's ndcg@5: 0.992503	valid_0's ndcg@10: 0.987841
[160]	valid_0's ndcg@5: 0.992503	valid_0's ndcg@10: 0.987841
[161]	valid_0's ndcg@5: 0.992503	valid_0's ndcg@10: 0.987867
[162]	valid_0's ndcg@5: 0.992503	valid_0's ndcg@10: 0.987867
[163]	valid_0's ndcg@5: 0.992503	valid_0's ndcg@10: 0.987867
[164]	valid_0's ndcg@5: 0.992867	valid_0's ndcg@10: 0.988104
[165]	valid_0's ndcg@5: 0.992867	valid_0's ndcg@10: 0.988104
[166]	valid_0's ndcg@5: 0.992867	valid_0's ndcg@10: 0.988104
[167]	valid_0's ndcg@5: 0.992675	valid_0's ndcg@10: 0.987978
[168]	valid_0's ndcg@5: 0.992675	valid_0's ndcg@10: 0.987978
[169]	valid_0's ndcg@5: 0.992867	valid_0's ndcg@10: 0.988104
[170]	valid_0's ndcg@5: 0.992867	valid_0's ndcg@10: 0.988104
[171]	valid_0's ndcg@5: 0.992867	valid_0's ndcg@10: 0.988104
[172]	valid_0's ndcg@5: 0.992867	valid_0's ndcg@10: 0.987582
[173]	valid_0's ndcg@5: 0.993111	valid_0's ndcg@10: 0.987714
[174]	valid_0's ndcg@5: 0.992989	valid_0's ndcg@10: 0.987635
[175]	valid_0's ndcg@5: 0.992989	valid_0's ndcg@10: 0.987635
[176]	valid_0's ndcg@5: 0.992989	valid_0's ndcg@10: 0.987635
Early stopping, best iteration is:
[126]	valid_0's ndcg@5: 0.994825	valid_0's ndcg@10: 0.987471
best_iteration: 126
val ndcg@10 curve (first 15 rounds): [0.9761594622640442, 0.9775834146904643, 0.9767597708640166, 0.9749576075848122, 0.9754970491543058, 0.9760126971382319, 0.974721558258085, 0.9754615352706988, 0.9751742214564488, 0.9735374791201746, 0.9739246159464702, 0.9734780993242396, 0.9736820653944194, 0.9742389785167005, 0.9746315072651907]

In [75]:
print("Number of trees in the ranker model:", ranker.num_trees())

# Get a small sample from the validation set for prediction
sample_val_df = val_df.head(10)
sample_predictions = ranker.predict(sample_val_df[FEATURE_COLS])

print("\nSample predictions on validation data (first 10 rows):\n")
for i, (item_id, prediction) in enumerate(zip(sample_val_df['item_id'], sample_predictions)):
    print(f"Item ID: {item_id}, Predicted Score: {prediction:.4f}")

Number of trees in the ranker model: 126

Sample predictions on validation data (first 10 rows):

Item ID: 3147, Predicted Score: -6.0946
Item ID: 70946, Predicted Score: -2.7016
Item ID: 5764, Predicted Score: -0.9376
Item ID: 4518, Predicted Score: -2.4548
Item ID: 26409, Predicted Score: -1.9877
Item ID: 7991, Predicted Score: -2.2530
Item ID: 2288, Predicted Score: 0.0326
Item ID: 849, Predicted Score: -3.2835
Item ID: 3024, Predicted Score: -1.2973
Item ID: 1587, Predicted Score: -2.3126

In [76]:
out_path = os.path.join(MODELS_DIR, "ranker.txt")
ranker.save_model(out_path)
print(f"Successfully updated ranker.txt at: {out_path}")

Successfully updated ranker.txt at: ./models/ranker.txt

In [69]:
import os

for file in os.listdir(MODELS_DIR):
    path = os.path.join(MODELS_DIR, file)
    print(f"{file:30} {os.path.getsize(path) / 1024:.2f} KB")

content_item_ids.npy           76.23 KB
content.index                  14613.04 KB
ranker.txt                     6.27 KB
content_embeddings.npy         14613.12 KB
ranker_features.json           0.06 KB
als_model.pkl                  2194.96 KB
ranking_train.csv              10328.56 KB

In [70]:
import os
import json
import pickle
import numpy as np
import pandas as pd
import faiss
import lightgbm as lgb

from sqlalchemy import create_engine, text
from dotenv import load_dotenv


load_dotenv()

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://recsys:recsys@localhost:5432/recsys"
)

MODELS_DIR = os.environ.get(
    "MODELS_DIR",
    "./models"
)


class Recommender:

    def __init__(self):

        print("Loading recommendation models...")

        self.engine = create_engine(DATABASE_URL)

        als_path = os.path.join(MODELS_DIR, "als_model.pkl")
        with open(als_path, "rb") as f:
            self.als = pickle.load(f)

        self.als_model = self.als["model"]
        self.user_id_to_idx = self.als["user_id_to_idx"]
        self.idx_to_user_id = self.als["idx_to_user_id"]
        self.item_id_to_idx = self.als["item_id_to_idx"]
        self.idx_to_item_id = self.als["idx_to_item_id"]

        self.embeddings = np.load(
            os.path.join(MODELS_DIR, "content_embeddings.npy")
        ).astype("float32")

        self.content_item_ids = np.load(
            os.path.join(MODELS_DIR, "content_item_ids.npy")
        )

        self.item_id_to_row = {
            int(item_id): index
            for index, item_id in enumerate(self.content_item_ids)
        }

        self.faiss_index = faiss.read_index(
            os.path.join(MODELS_DIR, "content.index")
        )

        self.ranker = lgb.Booster(
            model_file=os.path.join(MODELS_DIR, "ranker.txt")
        )

        with open(os.path.join(MODELS_DIR, "ranker_features.json")) as f:
            self.feature_cols = json.load(f)

        self.items = pd.read_sql(
            "SELECT id, title, genres, primary_genre FROM items",
            self.engine
        )

        self.item_genre = dict(zip(self.items["id"], self.items["primary_genre"]))

        # Precompute once instead of on every recommend() call
        self.item_lookup = self.items.set_index("id")

        interactions = pd.read_sql(
            "SELECT user_id, item_id, rating FROM interactions",
            self.engine
        )

        popularity = interactions.groupby("item_id").size()
        if len(popularity) > 0:
            popularity = (popularity / popularity.max()).to_dict()
        else:
            popularity = {}
        self.popularity = popularity

        print("All recommendation models loaded.")

    def _get_user_interactions(self, user_id):
        """Single source of truth for a user's interaction history —
        called once per recommend() and threaded through, instead of every
        stage re-querying Postgres for the same rows."""
        return pd.read_sql(
            text("SELECT item_id, rating FROM interactions WHERE user_id = :uid"),
            self.engine,
            params={"uid": int(user_id)},
        )

    def get_als_candidates(self, user_id, n=100):
        user_idx = self.user_id_to_idx.get(user_id)
        if user_idx is None:
            return []

        ids, scores = self.als_model.recommend(
            user_idx,
            self.als["user_item_matrix"][user_idx],
            N=n,
            filter_already_liked_items=True
        )

        candidates = []
        for item_idx, score in zip(ids, scores):
            item_id = self.idx_to_item_id[int(item_idx)]
            candidates.append({"item_id": int(item_id), "als_score": float(score)})

        return candidates

    def get_content_candidates(self, positive_items, n=100):
        if not positive_items:
            return []

        rows = [
            self.item_id_to_row[item_id]
            for item_id in positive_items
            if item_id in self.item_id_to_row
        ]
        if not rows:
            return []

        user_embedding = self.embeddings[rows].mean(axis=0)
        user_embedding = user_embedding / (np.linalg.norm(user_embedding) + 1e-8)
        user_embedding = user_embedding.reshape(1, -1).astype("float32")

        scores, indices = self.faiss_index.search(user_embedding, n)

        candidates = []
        seen_items = set(positive_items)
        for score, index in zip(scores[0], indices[0]):
            if index < 0:
                continue
            item_id = int(self.content_item_ids[index])
            if item_id in seen_items:
                continue
            candidates.append({"item_id": item_id, "content_sim": float(score)})

        return candidates

    def merge_candidates(self, als_candidates, content_candidates):
        merged = {}

        for candidate in als_candidates:
            item_id = candidate["item_id"]
            merged[item_id] = {
                "item_id": item_id,
                "als_score": candidate["als_score"],
                "content_sim": 0.0
            }

        for candidate in content_candidates:
            item_id = candidate["item_id"]
            if item_id not in merged:
                merged[item_id] = {
                    "item_id": item_id,
                    "als_score": 0.0,
                    "content_sim": candidate["content_sim"]
                }
            else:
                merged[item_id]["content_sim"] = candidate["content_sim"]

        return list(merged.values())

    def rank_candidates(self, candidates, user_genres):
        """positive_items/user_genres are passed in from recommend(), not
        re-queried here — avoids a duplicate DB round trip for data the
        caller already has."""
        if not candidates:
            return []

        rows = []
        for candidate in candidates:
            item_id = candidate["item_id"]
            genre = self.item_genre.get(item_id, "Unknown")
            genre_match = 1.0 if genre in user_genres else 0.0

            rows.append({
                "item_id": item_id,
                "als_score": candidate.get("als_score", 0.0),
                "content_sim": candidate.get("content_sim", 0.0),
                "popularity": self.popularity.get(item_id, 0.0),
                "genre_match": genre_match
            })

        features = pd.DataFrame(rows)
        predictions = self.ranker.predict(features[self.feature_cols])
        features["ranker_score"] = predictions

        features = features.sort_values("ranker_score", ascending=False).reset_index(drop=True)
        return features.to_dict(orient="records")

    def rerank(self, ranked_candidates, all_watched_items, max_per_genre=3, top_k=10):
        """Stage 3: business rules the ranker's score doesn't know about —
        drop anything already watched (liked OR disliked, not just positives),
        and cap how many items from one genre can dominate the top-k."""
        seen_genres = {}
        final = []
        for candidate in ranked_candidates:
            item_id = candidate["item_id"]
            if item_id in all_watched_items:
                continue
            genre = self.item_genre.get(item_id, "Unknown")
            if seen_genres.get(genre, 0) >= max_per_genre:
                continue
            seen_genres[genre] = seen_genres.get(genre, 0) + 1
            final.append(candidate)
            if len(final) >= top_k:
                break
        return final

    def recommend(self, user_id, n=10):
        user_interactions = self._get_user_interactions(user_id)
        all_watched_items = set(user_interactions["item_id"])
        positive_items = set(
            user_interactions[user_interactions["rating"] >= 4.0]["item_id"]
        )
        user_genres = {
            self.item_genre.get(item_id, "Unknown") for item_id in positive_items
        }

        als_candidates = self.get_als_candidates(user_id, n=100)
        content_candidates = self.get_content_candidates(list(positive_items), n=100)
        candidates = self.merge_candidates(als_candidates, content_candidates)

        ranked_candidates = self.rank_candidates(candidates, user_genres)
        if not ranked_candidates:
            return []

        final_candidates = self.rerank(ranked_candidates, all_watched_items, top_k=n)

        results = []
        for candidate in final_candidates:
            item_id = candidate["item_id"]
            if item_id not in self.item_lookup.index:
                continue
            movie = self.item_lookup.loc[item_id]
            results.append({
                "id": int(item_id),
                "title": movie["title"],
                "genres": movie["genres"],
                "score": float(candidate["ranker_score"]),
                "als_score": float(candidate["als_score"]),
                "content_sim": float(candidate["content_sim"]),
                "popularity": float(candidate["popularity"]),
                "genre_match": float(candidate["genre_match"]),
            })

        return results

In [71]:
def recommend_similar_movie(rec, movies, title, n=10):

    matches = movies[
        movies["title"].str.contains(
            title,
            case=False,
            na=False
        )
    ]

    if matches.empty:
        print(f"No movie found matching '{title}'")
        return

    selected = matches.iloc[0]

    movie_id = selected["movieId"]

    print("=" * 80)
    print(f"INPUT MOVIE: {selected['title']}")
    print(f"GENRES: {selected['genres']}")
    print("=" * 80)

    candidates = rec.get_content_candidates(
        positive_items=[movie_id],
        n=n
    )

    print("\nRECOMMENDED MOVIES")
    print("-" * 80)

    for i, candidate in enumerate(candidates, 1):

        candidate_id = candidate["item_id"]
        similarity = candidate["content_sim"]

        movie = movies[
            movies["movieId"] == candidate_id
        ]

        if movie.empty:
            continue

        row = movie.iloc[0]

        print(
            f"{i:2}. {row['title']:<50} "
            f"similarity={similarity:.4f} | "
            f"{row['genres']}"
        )

In [72]:
recommend_similar_movie(
    rec,
    movies,
    "toy story",
    n=10
)

NameError: name 'rec' is not defined